### ISSUE TITLE
guiBuilder compilation error

### ISSUE THREAD

**Issue by abisi** [BIOP/lightsheet-brain-workflows#1]
Hello, 
I wanted to test the code and GUI today but I came across a compilation error when clicking running guiBuilder.groovy in Fiji.

![image](https://github.com/BIOP/lightsheet-brain-workflows/assets/22441447/6e08196c-a01b-40e2-8d4e-0f3101504fd7)

The error message is clear, but somehow I feel like the error is something else given that I just pull the most recent code.
I tried removing the brackets at line 893, then the following error message is the same, but at the next line which also contains brackets.

Any ideas what could be the cause?

Thanks,
Axel

**Comment by abisi** [comment]
Ah, I just googled and there was just a "def" missing at this line:
https://github.com/BIOP/lightsheet-brain-workflows/blob/0aeee9e6070fbe6d8fe65f61aa6d3b9f7e4eedb0/src/main/groovy/guiBuilder.groovy#L893

 I made a fix but I am not a collaborator on the code so I cannot make any PR.

**Comment by lorenzotala** [comment]
Hi Axel,

Yeah sorry, I cleaned up the code (added comments and removed unsued variables) before leaving epfl but I didn't run the script one last time.

I might have mistakenly deleted the "def" before that.

**Comment by abisi** [comment]
Regarding this, if I am given permission to push, I could fix this.
