### ISSUE TITLE
Fused channel filename

### ISSUE THREAD

**Issue by abisi** [BIOP/lightsheet-brain-workflows#13]
Hello,

I tested yesterday and saw that the filename of the fused images, per channel, is wrong.
![image](https://github.com/user-attachments/assets/a36c171d-7131-4d5a-ae65-5683cdd1683b)
I think there is a missing /. In the image you see e.g. AB105.czi_fused_tp_0_ch_1.tif.

I suspect this is why brainreg didn't start.

**Comment by lacan** [comment]
The image name seems correct... Can you share the file so I can check it?

**Comment by abisi** [comment]
I think there is just the ".czi" in surplus in the filename, so there are two extensions.

**Comment by abisi** [comment]
If you can, the file is at the location on Peacock Spider (but booked currently)!

**Comment by lacan** [comment]
Yes the .czi is there to keep it somewhat consistent. I can remove it but if I look at the result this the actual file on my comptuer for another brain
![image](https://github.com/user-attachments/assets/6f8b1ede-3da4-44a6-b861-bb6b94b8a517)

**Comment by abisi** [comment]
Ah ok!
I thought it was a mistake.
But what happened after is that brainreg didn't start. I think it could not find the file. At the time I understood that the filename may have been an issue, and could not be found by the brainreg related code.

Does it work from A to Z on your end, especially the transition from fusion to brainreg?

Best,
Axel

Le 30 juil. 2024 à 15:53, Olivier Burri ***@***.***> a écrit :

﻿

Yes the .czi is there to keep it somewhat consistent. I can remove it but if I look at the result this the actual file on my comptuer for another brain
image.png (view on web)<https://github.com/user-attachments/assets/6f8b1ede-3da4-44a6-b861-bb6b94b8a517>

**Comment by abisi** [comment]
In the end this works.
