### ISSUE TITLE
Brainreg output files

### ISSUE THREAD

**Issue by abisi** [BIOP/lightsheet-brain-workflows#14]
Hello,

I had two questions regarding brainreg execution.

First, it seems that it uses docker, but I don't think we have installed an image or so?
Second, it would be good to have the output of brainreg saved in a separate folder "brainreg" that is at the same level as "fused".

Thanks!

**Comment by lacan** [comment]
If you specify the brainreg conda environment, it should use that one. 

It should shave the results under `brain\fused\registered` 
there was a bug where it was saving it under `AB001\fusedregistered`

I can change `registered` to `brainreg` no problem
